name: smartdigitalpsicouiproject
services:
  dashui: 
    image:  leonecr/smartdigitalpsicouihomolog:latest
    container_name:  smartdigitalpsicoui_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - "80" 
       - "4209"
    restart: always
