version: '3.4' 
name: sdpsic-ui-project
services:
  dashui: 
    image:  sdp_ui_dash_cloud_image_v2 
    container_name:  sdp_ui_dash_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - "80:80" 
       - "4209:4209"
    restart: always
