/**
 * SmartDigitalPsico.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type EStatusCalendar = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

export const EStatusCalendar = {
    NUMBER_0: 0 as EStatusCalendar,
    NUMBER_1: 1 as EStatusCalendar,
    NUMBER_2: 2 as EStatusCalendar,
    NUMBER_3: 3 as EStatusCalendar,
    NUMBER_4: 4 as EStatusCalendar,
    NUMBER_5: 5 as EStatusCalendar,
    NUMBER_6: 6 as EStatusCalendar,
    NUMBER_7: 7 as EStatusCalendar,
    NUMBER_8: 8 as EStatusCalendar,
    NUMBER_9: 9 as EStatusCalendar,
    NUMBER_10: 10 as EStatusCalendar
};