/**
 * SmartDigitalPsico.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ETypeAccreditation = 0 | 1;

export const ETypeAccreditation = {
    NUMBER_0: 0 as ETypeAccreditation,
    NUMBER_1: 1 as ETypeAccreditation
};