/**
 * SmartDigitalPsico.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DayOfWeek } from './dayOfWeek';
import { ETypeAccreditation } from './eTypeAccreditation';
import { GetOfficeDto } from './getOfficeDto';
import { GetPatientDto } from './getPatientDto';
import { GetSpecialtyDto } from './getSpecialtyDto';
import { HyperMediaLink } from './hyperMediaLink';

export interface GetMedicalDto { 
    id?: number;
    enable?: boolean;
    name?: string;
    office?: GetOfficeDto;
    specialties?: Array<GetSpecialtyDto>;
    patients?: Array<GetPatientDto>;
    email?: string;
    accreditation?: string;
    typeAccreditation?: ETypeAccreditation;
    workingDays?: Array<DayOfWeek>;
    links?: Array<HyperMediaLink>;
}