/**
 * SmartDigitalPsico.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetPatientDto } from './getPatientDto';
import { HyperMediaLink } from './hyperMediaLink';

export interface GetPatientMedicationInformationDto { 
    id?: number;
    enable?: boolean;
    patient?: GetPatientDto;
    links?: Array<HyperMediaLink>;
    description?: string;
    startDate?: Date;
    endDate?: Date;
    dosage?: string;
    posology?: string;
    mainDrug?: string;
}