/**
 * SmartDigitalPsico.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HyperMediaLink } from './hyperMediaLink';

export interface NotificationTemplateDto { 
    subject?: string;
    body?: string;
    description?: string;
    language?: string;
    links?: Array<HyperMediaLink>;
    id?: number;
    enable: boolean; 
    tagApi?: string;
}