/**
 * SmartDigitalPsico.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UpdateMedicalDto } from './updateMedicalDto';

export interface UpdateUserProfileDto { 
    id?: number;
    enable?: boolean;
    name?: string;
    email?: string;
    medical?: UpdateMedicalDto;
    password?: string;
    language?: string;
    timeZone?: string;
}