/**
 * SmartDigitalPsico.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DayOfWeek } from './dayOfWeek';
import { ETypeAccreditation } from './eTypeAccreditation';

export interface UpdateMedicalDto { 
    id?: number;
    enable?: boolean;
    officeId?: number;
    specialtiesIds?: Array<number>;
    name?: string;
    email?: string;
    accreditation?: string;
    typeAccreditation?: ETypeAccreditation;
    workingDays?: Array<DayOfWeek>;
}