/**
 * SmartDigitalPsico.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserRegisterDto { 
    enable?: boolean;
    roleGroupsIds?: Array<number>;
    medicalId?: number;
    name?: string;
    email?: string;
    login?: string;
    password?: string;
    role?: string;
    admin?: boolean;
    language?: string;
    timeZone?: string;
}